// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhuecgdtaszobhkpkssr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodWVjZ2R0YXN6b2Joa3Brc3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzIwNjMsImV4cCI6MjA1MzA0ODA2M30.sE5nA8ofh0rNeygIDr2heL77HKjO_NeSkV4uijHKBeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);